### ISSUE TITLE
readme?

### ISSUE THREAD

**Issue by awrebels** [aciodev/TwitchChatFrequency#1]
just found this and wondering if you have a more up to date readme, or how to use. 

i seem to be running into some runtime errors and wondering if I'm missing something 

thanks for making this!

**Comment by aciodev** [comment]
Hello! Which runtime errors are you encountering? I will update the README with more information on how to use this tool.

**Comment by awrebels** [comment]
thanks! Actually your updated files and readme helped, and work great! tested the commands and they work well. 

One thing (which I can create a different issue if you prefer) is if during polling you could see the live results OR perhaps easier print current results without the poll ending. The res command seems to end the polling and print results. 

thanks!

**Comment by aciodev** [comment]
Hello, again! That is a solid suggestion. The `res` command no longer clears the collected chat messages. Instead, you can use `poll` to reset that data and begin polling again.

Let me know if you have further thoughts!
